version: "2"
services:
  api:
    image: "paulofilipem/go-engine-core:v1.0.2"
    volumes:
      - './:/var/www'
    ports:
      - 8086:80
    environment:
      - "externalBaseUrl=http://localhost:8086"
      
