version: "2"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "composer install --ignore-platform-reqs"
    ports:
     - "9090:80"
    volumes:
     - .:/var/www
